server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: hemogram-monitoring
  
  # Configuração do banco H2 (para desenvolvimento)
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configuração de logging
logging:
  level:
    com.ubiquo.hemogrammonitoring: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configurações específicas do sistema
hemogram:
  monitoring:
    # Configurações do servidor FHIR
    fhir:
      server-url: "http://localhost:8080/fhir" # Servidor FHIR local
      subscription:
        enabled: true # Habilita criação automática de subscription
        callback-url: "http://localhost:8081/fhir/subscription" # URL que o servidor FHIR chamará
        criteria: "Observation?code=777-3" # Filtro: Observations com plaquetas (mais amplo para testes)
    
    # Valores de referência (podem ser sobrescritos por configuração)
    reference-values:
      leucocitos:
        min: 4000
        max: 11000
      hemoglobina:
        min: 12.0
        max: 17.5
      plaquetas:
        min: 150000
        max: 450000
      hematocrito:
        min: 36.0
        max: 52.0
    
    # Configurações de alerta
    alerts:
      dengue-threshold: 150000 # Plaquetas abaixo deste valor indicam possível dengue
      region: "Goiânia" # Região padrão para testes
